-- Natural Selection 2 Competitive Mod
-- Source located at - https://github.com/xToken/CompMod
-- lua\CompMod_Shared.lua
-- - Dragon

-- Base 'Shared' changes which apply to all VMs

Script.Load("lua/Class.lua")
Script.Load("lua/CompMod/Utilities/Elixer/shared.lua")

Elixer.UseVersion( 1.8 )

kCompModBuild = 25

Script.Load("lua/CompMod/AlienSensorBlip/shared.lua")
Script.Load("lua/CompMod/Damage/shared.lua")
Script.Load("lua/CompMod/NS2Utility/shared.lua")
Script.Load("lua/CompMod/TeamInfo/shared.lua")
Script.Load("lua/CompMod/SpawnAngleFix/shared.lua")

Script.Load("lua/CompMod/Classes/Alien/Alien/shared.lua")
Script.Load("lua/CompMod/Classes/Alien/AlienCommander/shared.lua")
Script.Load("lua/CompMod/Classes/Alien/Babbler/shared.lua")
Script.Load("lua/CompMod/Classes/Alien/Egg/shared.lua")
Script.Load("lua/CompMod/Classes/Alien/Fade/shared.lua")
Script.Load("lua/CompMod/Classes/Alien/Gorge/shared.lua")
Script.Load("lua/CompMod/Classes/Alien/Lerk/shared.lua")
Script.Load("lua/CompMod/Classes/Alien/Onos/shared.lua")
Script.Load("lua/CompMod/Classes/Alien/Skulk/shared.lua")
Script.Load("lua/CompMod/Classes/Marine/Exo/shared.lua")
Script.Load("lua/CompMod/Classes/Marine/Exosuit/shared.lua")
Script.Load("lua/CompMod/Classes/Marine/JetpackMarine/shared.lua")
Script.Load("lua/CompMod/Classes/Marine/Marine/shared.lua")
Script.Load("lua/CompMod/Classes/Marine/MarineCommander/shared.lua")
Script.Load("lua/CompMod/Classes/Player/shared.lua")

Script.Load("lua/CompMod/CommAbilities/EnzymeCloud/shared.lua")
Script.Load("lua/CompMod/CommAbilities/HallucinationCloud/shared.lua")
Script.Load("lua/CompMod/CommAbilities/MucousMembrane/shared.lua")
Script.Load("lua/CompMod/CommAbilities/NutrientMist/shared.lua")
Script.Load("lua/CompMod/CommAbilities/ParasiteCloud/shared.lua")
Script.Load("lua/CompMod/CommAbilities/Rupture/shared.lua")

Script.Load("lua/CompMod/Mixins/ConstructMixin/shared.lua")
Script.Load("lua/CompMod/Mixins/InfestationMixin/shared.lua")
Script.Load("lua/CompMod/Mixins/MaturityMixin/shared.lua")
Script.Load("lua/CompMod/Mixins/NanoShieldMixin/shared.lua")
Script.Load("lua/CompMod/Mixins/WalkMixin/shared.lua")
Script.Load("lua/CompMod/Mixins/WeaponOwnerMixin/shared.lua")

Script.Load("lua/CompMod/Structures/Alien/BabblerEgg/shared.lua")
Script.Load("lua/CompMod/Structures/Alien/Crag/shared.lua")
Script.Load("lua/CompMod/Structures/Alien/Cyst/shared.lua")
Script.Load("lua/CompMod/Structures/Alien/Drifter/shared.lua")
Script.Load("lua/CompMod/Structures/Alien/EvolutionChamber/shared.lua")
Script.Load("lua/CompMod/Structures/Alien/Harvester/shared.lua")
Script.Load("lua/CompMod/Structures/Alien/Hive/shared.lua")
Script.Load("lua/CompMod/Structures/Alien/Hydra/shared.lua")
Script.Load("lua/CompMod/Structures/Alien/Shade/shared.lua")
Script.Load("lua/CompMod/Structures/Alien/Shell/shared.lua")
Script.Load("lua/CompMod/Structures/Alien/Shift/shared.lua")
Script.Load("lua/CompMod/Structures/Alien/Spur/shared.lua")
Script.Load("lua/CompMod/Structures/Alien/Veil/shared.lua")
Script.Load("lua/CompMod/Structures/Alien/Web/shared.lua")
Script.Load("lua/CompMod/Structures/Alien/InfestedNode/shared.lua")

Script.Load("lua/CompMod/Structures/Marine/ARC/shared.lua")
Script.Load("lua/CompMod/Structures/Marine/Armory/shared.lua")
Script.Load("lua/CompMod/Structures/Marine/ArmsLab/shared.lua")
Script.Load("lua/CompMod/Structures/Marine/CommandStation/shared.lua")
Script.Load("lua/CompMod/Structures/Marine/Observatory/shared.lua")
Script.Load("lua/CompMod/Structures/Marine/PhaseGate/shared.lua")
Script.Load("lua/CompMod/Structures/Marine/PowerPoint/shared.lua")
Script.Load("lua/CompMod/Structures/Marine/PrototypeLab/shared.lua")
Script.Load("lua/CompMod/Structures/Marine/RoboticsFactory/shared.lua")
Script.Load("lua/CompMod/Structures/Marine/PowerNode/shared.lua")

Script.Load("lua/CompMod/Weapons/Alien/Ability/shared.lua")
Script.Load("lua/CompMod/Weapons/Alien/BiteLeap/shared.lua")
Script.Load("lua/CompMod/Weapons/Alien/Blink/shared.lua")
Script.Load("lua/CompMod/Weapons/Alien/LerkBite/shared.lua")
Script.Load("lua/CompMod/Weapons/Alien/SporeCloud/shared.lua")
Script.Load("lua/CompMod/Weapons/Marine/Axe/shared.lua")
Script.Load("lua/CompMod/Weapons/Marine/ClusterGrenade/shared.lua")
Script.Load("lua/CompMod/Weapons/Marine/Flamethrower/shared.lua")
Script.Load("lua/CompMod/Weapons/Marine/FlameCloud/shared.lua")
Script.Load("lua/CompMod/Weapons/Marine/Grenade/shared.lua")
Script.Load("lua/CompMod/Weapons/Marine/GrenadeFragment/shared.lua")
Script.Load("lua/CompMod/Weapons/Marine/GrenadeLauncher/shared.lua")
Script.Load("lua/CompMod/Weapons/Marine/HeavyMachineGun/shared.lua")
Script.Load("lua/CompMod/Weapons/Marine/LayMines/shared.lua")
Script.Load("lua/CompMod/Weapons/Marine/Mine/shared.lua")
Script.Load("lua/CompMod/Weapons/Marine/Minigun/shared.lua")
Script.Load("lua/CompMod/Weapons/Marine/PulseGrenade/shared.lua")
Script.Load("lua/CompMod/Weapons/Marine/Railgun/shared.lua")
Script.Load("lua/CompMod/Weapons/Marine/Shotgun/shared.lua")
Script.Load("lua/CompMod/Weapons/Marine/Welder/shared.lua")
Script.Load("lua/CompMod/Weapons/Weapon/shared.lua")